defaults: &defaults
  pool: 5
  timeout: 5000
  reconnect: false
  encoding: utf8

sqlite: &sqlite
  adapter: sqlite3
  database: db/dev.sqlite3

test:
  database: db/test.sqlite3
  <<: *defaults
  <<: *sqlite

production: &production
  adapter: mysql2
  database: <%=ENV['OPENSHIFT_APP_NAME']%>
  username: <%=ENV['OPENSHIFT_MYSQL_DB_USERNAME']%>
  password: <%=ENV['OPENSHIFT_MYSQL_DB_PASSWORD']%>
  host:     <%=ENV['OPENSHIFT_MYSQL_DB_HOST']%>
  port:     <%=ENV['OPENSHIFT_MYSQL_DB_PORT']%>
  <<: *defaults

development:
  <<: *<%=ENV['OPENSHIFT_APP_NAME'] ? "production" : "sqlite"%>
  <<: *defaults
